# https://pnpm.io/settings#blockexoticsubdeps
blockExoticSubdeps: true

# https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 1440

# https://pnpm.io/settings#onlybuiltdependencies
onlyBuiltDependencies:
  - pg

# https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true

# https://pnpm.io/settings#trustpolicy
trustPolicy: "no-downgrade"

# https://pnpm.io/settings#auditlevel
auditLevel: "high"
