// SPDX-FileCopyrightText: 2026 Padparadscho <contact@padparadscho.com>
// SPDX-License-Identifier: GPL-3.0-only

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Events {
  data: string | null;
  escrow_balance: string | null;
  id: string;
  ledger_closed_at: Timestamp | null;
  ledger_sequence: Int8 | null;
  processed: Generated<boolean>;
  topics: string | null;
  transaction_hash: string | null;
  unit_price: Numeric | null;
}

export interface Transfers {
  amount: Numeric | null;
  id: string;
  ledger_closed_at: Timestamp | null;
  ledger_sequence: Int8 | null;
  processed: Generated<boolean>;
  recipient: string | null;
  sender: string | null;
  transaction_hash: string | null;
  transfer_type: string | null;
  unit_price: Numeric | null;
}

export interface DB {
  events: Events;
  transfers: Transfers;
}
